### ISSUE TITLE
Bid rules

### ISSUE THREAD

**Issue by bregnvig** [bregnvig/F2020#2]
### Dokument placering

`season/{seasonId}/races/{raceId}/bids/{uid}`

### Skrivning

Det skal være muligt at skrive et bud hvis race state er `open` og bid dokumentet enten ikke eksisterer eller bid state er `draft`. .Bid state ska også være `draft` ved oprettelse. Penge er ikke vigtige på det her tidspunkt

På den måde kan vi gemme halve bud og brugeren kan vende tilbage senere.

**Roller**: player

### Læsning

Det skal være muligt at læse et bud hvis race state ikke er `open` eller hvis spilleren har et bid dokument med state `confirmed`.På den måde burde man kunne se folk lave deres bud real time. Så længe man selv har budt.

Google functions er det eneste der kan sætte bid state i `completed`

**Roller**: player

**Comment by mbart71** [comment]
Der er lagt en regl ind  nu - som gør overstående, men det kræver at races state er open for at der kan lave bids - så jeg har manuelt ændret Austrailia til open (var waiting).  Derudover mangler der en state i de bids der er oprette, for at jeg kan se om den er i draft eller om den er completed. Når de er inde kan vi rette den nuværende regl til.
```
match /season/{Season}/races/{Races}/bids/{Bids} {
     // allow to create bid if race is open and a bid does not already exsist 
     allow create if getUserData().role.hasAny(['player']) 
                    && get(/databases/$(database)/documents/season/$(Season)/races/$(Races)).data.state == 'open' 
                    && !exists(/databases/$(database)/documents/season/$(Season)/races/$(Races)/bids/$(request.auth.uid));
     allow update if getUserData().role.hasAny(['player']) 
                    && get(/databases/$(database)/documents/season/$(Season)/races/$(Races)).data.state == 'open' 
                    && get(/databases/$(database)/documents/season/$(Season)/races/$(Races)/bids/$(request.auth.uid))data.state != "completed";               
     // allow to read bids if races is waiting or closed - or if bid is your own - or read all bids if you have made your bid             
     allow read: if getUserData().role.hasAny(['player']) 
                    && get(/databases/$(database)/documents/season/$(Season)/races/$(Races)).data.state != 'open' 
                    || getUserData().role.hasAny(['player'])
                    &&  request.auth.uid == Bids 
                    || getUserData().role.hasAny(['player']) 
                    && exists(/databases/$(database)/documents/season/$(Season)/races/$(Races)/bids/$(request.auth.uid))
                    && get(/databases/$(database)/documents/season/$(Season)/races/$(Races)/bids/$(request.auth.uid))data.state != "draft";  
    }
```

**Comment by bregnvig** [comment]
Jeg tænker  at i stedet for at benytte state, hvilket er lidt irriterende for mig, så kunne vi nøjes med at tilføje en property på bid som `submitted: true`

Kan vi få nogle flere parenteser om && || udtrykkende? Eks.:

```
get(/databases/$(database)/documents/season/$(Season)/races/$(Races)).data.state != 'open' 
                    || getUserData().role.hasAny(['player'])
```

til 

```
(get(/databases/$(database)/documents/season/$(Season)/races/$(Races)).data.state != 'open' 
                    || getUserData().role.hasAny(['player']))
```
